export const actions = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  SET_BOOKS: 'SET_BOOKS',
  COUNT_BOOKS: 'COUNT_BOOKS',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  SET_MODAL_TYPE: 'SET_MODAL_TYPE',
  SIGN_UP: 'SIGN_UP',
};
