export const actions = {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  SET_BOOKS: 'SET_BOOKS',
  LOADING_BOOKS: 'LOADING_BOOKS',
  COUNT_BOOKS: 'COUNT_BOOKS',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  SET_MODAL_TYPE: 'SET_MODAL_TYPE',
  AUTH: 'AUTH',
  SIGN_OUT: 'SIGN_OUT',
};
